---
apiVersion: v1
kind: ConfigMap
metadata:
  name: podinfo-env
  namespace: apps
data:
  PODINFO_UI_MESSAGE: "âœ¨ðŸŽ¢ CloudLand 2023 R0ckX hard in Production ðŸŽ¸âœ¨"
  PODINFO_BACKEND_URL: "http://podinfo.apps/echo"
